### ISSUE TITLE
Geordi writes wrong string to the global settings

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#114]
I recently had the following error. I will submit it here for documentation purpose, because I'm not sure if this happens to other users, too.

```
/home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: HighLine::String (Psych::DisallowedClass)
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/class_loader.rb:28:in `load'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:66:in `deserialize'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:302:in `safe_load'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/settings.rb:73:in `read_settings'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/settings.rb:15:in `initialize'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/cucumber.rb:20:in `new'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/cucumber.rb:20:in `run'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/commands/cucumber.rb:79:in `cucumber'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/exe/geordi:10:in `block in <top (required)>'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/lib/geordi/util.rb:13:in `installing_missing_gems'
	from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geordi-4.1.1/exe/geordi:5:in `<top (required)>'
	from /home/user/.rbenv/versions/2.3.1/bin/geordi:23:in `load'
	from /home/user/.rbenv/versions/2.3.1/bin/geordi:23:in `<main>'
```

```
% cat ~/.config/geordi/global.yml
---
pivotal_tracker_api_key: !ruby/string:HighLine::String ''
```

**Comment by denzelem** [comment]
I will close this issue until someone else has the same issue or it will pop up for me a second time. Until now, deleting the file `~/.config/geordi/global.yml` was a proper fix.

**Comment by codener** [comment]
Would like to examine this.

**Comment by codener** [comment]
Had a look. Culprit must be https://github.com/makandra/geordi/blob/7ead036905655fd3c0a70758568a59f042fcb565/lib/geordi/settings.rb#L20 where if no `~/.gitpt` file exists, the API token is requested and written to the settings hash, which gets persisted by `#to_yaml`. While I couldn't reproduce the `Highline::String` dump, it may be caused by another version of Highline. 

To be sure, I'll just cast the value received from Highline to a normal string.
