### ISSUE TITLE
geordi devserver doesn't start with ruby-1.8.7-p374 and railslts-0942fbd53b0b

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#17]
```
> g dev

# Booting a development server
> URL: http://foo.vcap.me:3000

/home/bar/.rvm/gems/ruby-1.8.7-p374/bundler/gems/railslts-0942fbd53b0b/activesupport/lib/active_support/dependencies.rb:182:in `require': no such file to load -- rack/handler/-p (MissingSourceFile)
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/bundler/gems/railslts-0942fbd53b0b/activesupport/lib/active_support/dependencies.rb:182:in `require'
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/bundler/gems/railslts-0942fbd53b0b/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/bundler/gems/railslts-0942fbd53b0b/activesupport/lib/active_support/dependencies.rb:182:in `require'
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/gems/rack-1.4.7/lib/rack/handler.rb:63:in `try_require'
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/gems/rack-1.4.7/lib/rack/handler.rb:16:in `get'
    from /home/bar/.rvm/gems/ruby-1.8.7-p374/bundler/gems/railslts-0942fbd53b0b/railties/lib/commands/server.rb:45
    from script/server:3:in `require'
    from script/server:3
```

`script/server` however works.

**Comment by codener** [comment]
This is not Geordi's fault – in former times, `script/server` has accepted an argument `-p PORT`, which now fails.

Todo: Investigate, what's wrong with passing a port to `script/server`.

**Comment by henning-koch** [comment]
If my project has switched to Thin by addeding `thin` the Gemfile, I can still boot webrick by saying `script/server webrick`. @denzelem's exception looks like `script/server` is trying to boot the `-p` webserver.

**Comment by codener** [comment]
Possible fix: add empty argument before passing options: `script/server '' -p 3001`. But why is this needed now and hasn't been before?

**Comment by codener** [comment]
@denzelem let's talk about this and try it again with the concerned application.
