### ISSUE TITLE
`geordi cucumber` crashes with `--format=pretty`

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#37]
The README says any unknown command line will be passed to Cucumber. However, when I call `geordi cucumber` with `--format=pretty` I'm getting the following error:

```
geordi cucumber features/project/memos/crud.feature:67 --format=pretty

# Running features
> Only: features/project/memos/crud.feature:67
> VNC is ready to hold Selenium test browsers. Use `geordi vnc` to view them.

All but one formatter must use --out, only one can print to each stream (or STDOUT) (RuntimeError)
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/options.rb:292:in `check_formatter_stream_conflicts'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/options.rb:274:in `parse!'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/configuration.rb:26:in `parse!'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:65:in `block in configuration'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:64:in `tap'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:64:in `configuration'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
/home/henning/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-2.1.0/bin/cucumber:8:in `<top (required)>'
/home/henning/.rbenv/versions/2.4.1/bin/cucumber:23:in `load'
/home/henning/.rbenv/versions/2.4.1/bin/cucumber:23:in `<main>'
```

This is with Cucumber 2.1.0.

**Comment by codener** [comment]
True, this is not how it should be.
You can get format "pretty" with the `--debug` option until this is fixed.
