### ISSUE TITLE
`geordi console` raises an error in Rails 3.2 project

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#82]
Hi! I'm using the latest Geordi 2.10.1 in a project with Rails LTS 3.2.22.13.

When I am using `geordi console` I get an error "invalid option: -e":

```
geordi console production

# Opening a Rails console on production
> Connecting to foo.bar.de
Traceback (most recent call last):
	6: from script/rails:6:in `<main>'
	5: from script/rails:6:in `require'
	4: from /var/www/makandracards.com/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.13/lib/rails/commands.rb:41:in `<top (required)>'
	3: from /var/www/makandracards.com/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.13/lib/rails/commands/console.rb:8:in `start'
	2: from /var/www/makandracards.com/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.13/lib/rails/commands/console.rb:18:in `start'
	1: from /var/www/makandracards.com/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.13/lib/rails/commands/console.rb:18:in `new'
/var/www/makandracards.com/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.13/lib/rails/commands/console.rb:23:in `block in start': invalid option: -e (OptionParser::InvalidOption)
Connection to foo.bar.de closed.

x Something went wrong.
```

Background is that Rails 3.2 doesn't accept `rails console -e production`, it wants `rails console production`.

I saw that  [`Geordi::Util` is checking against the major Rails version](https://github.com/makandra/geordi/blob/761782c9a4d44ba5ed89b8d88da071a146608d63/lib/geordi/util.rb#L66) and should omit the `-e` in Rails 3. Maybe that check does not work properly?

**Comment by denzelem** [comment]
Hi @triskweline,

I was not able to reproduce this issue. Can you please execute this code snippet in an `irb` shell within the project root?

```
require 'geordi/version'
require 'geordi/util'

module GeordiUtilDebugExtension
  def self.prepended(base)
    base.singleton_class.send(:prepend, ClassMethods)
  end

  module ClassMethods
    def console_command(*)
      result = super

      p ['Called command', result]
      p ['Detected Rails major version', gem_major_version('rails')]
      p ['Detected Rails version', gem_version('rails')]
      p ['Geordi version', Geordi::VERSION]

      result
    end
  end
end

Geordi::Util.prepend(GeordiUtilDebugExtension)

Geordi::Util.installing_missing_gems do
  require 'rubygems' unless defined?(Gem)
  require 'geordi'
  require 'thor'

  Geordi::CLI.start(['console', 'production'])
end
```

I hope this helps to figure out, why the command is working for me like expected:

```
# Opening a Rails console on production
["Called command", "bundle exec rails console production"]
["Detected Rails major version", 3]
["Detected Rails version", #<Gem::Version "3.2.22.13">]
["Geordi version", "2.10.1"]
> Connecting to foo.bar.de
Loading production environment (Rails 3.2.22.1)
irb(main):001:0>
```

**Comment by triskweline** [comment]
I cannot reproduce the issue anymore either :( Sorry for the trouble, and thanks for preparing the debugging code.
