### ISSUE TITLE
Traceback of Geordi 3 is too long

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#92]
I recently notices that Geordi 3 has a longer backtrace than Geordi 2 for `geordi rspec`. The section `Traceback (most recent call last)` is not present in Geordi 2. We moved the binaries from `bin` to `exe`, but this should not lead to any changes on the host systems.

## Geordi 3.0.0 

```
     # ./app/models/some.rb:41:in `refresh'
     # ./spec/some_spec.rb:107:in `block (4 levels) in <main>'
     # ./spec/some_spec.rb:11:in `block (2 levels) in <main>'
     # /home/user/Projects/test_project/spec/support/shellout.rb:81:in `block (2 levels) in <main>'

Finished in 0.52709 seconds (files took 1.83 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/some_spec.rb:98 # Some error message

Randomized with seed 14300

Traceback (most recent call last):
	10: from /home/user/.rbenv/versions/2.6.6/bin/geordi:23:in `<main>'
	 9: from /home/user/.rbenv/versions/2.6.6/bin/geordi:23:in `load'
	 8: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/geordi-3.0.0/exe/geordi:5:in `<top (required)>'
	 7: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/geordi-3.0.0/lib/geordi/util.rb:14:in `installing_missing_gems'
	 6: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/geordi-3.0.0/exe/geordi:10:in `block in <top (required)>'
	 5: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 4: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 3: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 2: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 1: from /home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/geordi-3.0.0/lib/geordi/commands/rspec.rb:41:in `rspec'
/home/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/geordi-3.0.0/lib/geordi/util.rb:62:in `system!': Specs failed. (RuntimeError)
```
## Geordi 2.11.0

```
     # ./app/models/some.rb:41:in `refresh'
     # ./spec/some_spec.rb:107:in `block (4 levels) in <main>'
     # ./spec/some_spec.rb:11:in `block (2 levels) in <main>'
     # /home/user/Projects/test_project/spec/support/shellout.rb:81:in `block (2 levels) in <main>'

Finished in 0.41415 seconds (files took 2.06 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/some_spec.rb:98 # Some error message

Randomized with seed 55165


x Specs failed.
```

**Comment by denzelem** [comment]
Renaming `fail` to `raise` here was wrong, `fail` is a method defined in Geordi itself. Maybe we can use a different naming.
