### ISSUE TITLE
`geordi drop-databases` does not work with version 3.0.0

### ISSUE THREAD

**Issue by FLeinzi** [makandra/geordi#93]
Hey there,

I can't use the command `geordi drop-database` in version `3.0.0` anymore. I get prompted to enter my sudo password, but then the task fails with this message:

```
Traceback (most recent call last):
11: from .../bin/geordi:23:in `<main>'
10: from .../bin/geordi:23:in `load'
 9: from .../geordi-3.0.0/exe/geordi:5:in `<top (required)>'
 8: from .../geordi-3.0.0/lib/geordi/util.rb:14:in `installing_missing_gems'
 7: from .../geordi-3.0.0/exe/geordi:10:in `block in <top (required)>'
 6: from .../thor-1.0.1/lib/thor/base.rb:485:in `start'
 5: from .../thor-1.0.1/lib/thor.rb:392:in `dispatch'
 4: from .../thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
 3: from .../thor-1.0.1/lib/thor/command.rb:27:in `run'
 2: from .../geordi-3.0.0/lib/geordi/commands/drop_databases.rb:53:in `drop_databases'
 1: from .../geordi-3.0.0/lib/geordi/commands/drop_databases.rb:53:in `new'

.../geordi-3.0.0/lib/geordi/db_cleaner.rb:14:in `initialize': 
sudo access is required for database operations as database users (RuntimeError)
```
I have tried it with different versions of ruby, e.g. `ruby 2.5.0p0`.

It still works with `geordi 2.11.0`

**Comment by denzelem** [comment]
@FLeinzi This should be fixed, thanks for reporting the issue. Please upgrade to the patched version of geordi `gem install geordi -v '3.0.1'`.

**Comment by FLeinzi** [comment]
Thanks, works!
